### ISSUE TITLE
[5] PATCH project/:slug endpoint

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#98] opened 2015-08-04 22:34 UTC
Write tests for an implement PATCH for a given project's owner / slugs / uri / name values.
User will hit ``/projects/:slug`` with a json body containing the new information (new owner / activity / uri / name values) for that slug's corresponding project.

**Comment by tschuy** [comment] 2015-08-04 22:38
Duplicate of https://github.com/osuosl/timesync-node/issues/30

**Closed** 2015-08-04 22:43 UTC
