### ISSUE TITLE
ILLEGAL token in activities.js

### ISSUE THREAD

**Issue by Kennric** [osuosl/timesync-node#303] opened 2016-07-15 22:51 UTC
Line 280 generates an error:
```
      return errors.send(errors.errorBadObjectInvalidField('activity', 'slug',
                          'valid slug', `invalid slug ${currObj.slug}`), res);
```

The error:

```
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/timesync/source/src/app.js:111:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
    at Module._compile (module.js:460:26)
/opt/timesync/source/src/activities.js:280
                          'valid slug', `invalid slug ${currObj.slug}`), res);
                                        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)

```
The illegal token appears to be the backtick ` - replacing this with ' seems to fix the 503 error.

**Comment by Kennric** [comment] 2016-07-15 23:00
replacing the backtick with single-quote causes this test to fail:

```
  1) Endpoints POST /activities/:slug fails to update when given an invalid slug:

      Uncaught AssertionError: expected { Object (status, error, ...) } to deeply equal { Object (status, error, ...) }
      + expected - actual

       {
         "error": "Bad object"
         "status": 400
      -  "text": "Field slug of activity should be valid slug but was sent as invalid slug ${currObj.slug}"
      +  "text": "Field slug of activity should be valid slug but was sent as invalid slug activity--!@#$"
       }
```

Clearly the backticks should have been interpolating ${currObj.slug}, but seem to cause a syntax error in production. Is this maybe the result of an environmental difference on the prod server?

@LyonesGamer @ElijahCaine

**Comment by LyonesGamer** [comment] 2016-08-04 18:54
Issue was caused by an outdated version of Node.js on the server, which did not support string templates. Problem is fixed now.

**Closed by LyonesGamer** 2016-08-04 18:54 UTC
